---
version: '3'

services:
  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.9.7
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.rule=Host(`${TAUTULLI_URL}`)"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.tls.certresolver=default"
      - "traefik.http.routers.tautulli.middlewares=secHeaders@file"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
