---
version: '3'
  
services:
  guacamole_guacd:
    image: guacamole/guacd:latest
    container_name: guacamole_guacd
    restart: unless-stopped
  
  guacamole_mysql:
    image: mysql:latest
    container_name: guacamole_mysql
    restart: unless-stopped
    volumes:
      - /var/docker/data/guacamole/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Setze hier ein starkes Passwort
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_sql
      - MYSQL_PASSWORD= # Ein anderes Passwort

  guacamole_guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole_guacamole
    restart: unless-stopped
    environment:
      - MYSQL_HOSTNAME=guacamole_mysql
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_sql
      - MYSQL_PASSWORD=
      - GUACD_HOSTNAME=guacamole_guacd
      - GUACD_PORT=4822
    links:
      - guacamole_guacd:guacd
      - guacamole_mysql:mysql
    depends_on:
      - guacamole_guacd
      - guacamole_mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.guacamole-https.redirectscheme.scheme=https"
      - "traefik.http.routers.guacamole-http.entrypoints=web"
      - "traefik.http.routers.guacamole-http.rule=Host(`guacamole.example.com`)" #Domain anpassen
      - "traefik.http.routers.guacamole-http.middlewares=guacamole-https@docker"
      - "traefik.http.routers.guacamole.entrypoints=web-secure"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.example.com`)" #Domain anpassen
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.tls.certresolver=default"
      - "traefik.http.routers.guacamole.middlewares=secHeaders@file"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
    network:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge