---
version: '3.3'

services:
  bookstack-db:
    image: mysql:5.7
    container_name: bookstack-db
    restart: always
    volumes:
      - /var/docker/bookstack/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Setze hier ein starkes Passwort
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD= # Ein anderes Passwort

  # bookstack-db-backup:
  #   image: databack/mysql-backup
  #   container_name: bookstack-db-backup
  #   depends_on:
  #     - bookstack-db
  #   restart: always
  #   volumes:
  #     - /var/docker/bookstack/backup:/db
  #   environment:
  #     - DB_DUMP_FREQ=60 # Backup jede Stunde - Angabe in Minuten
  #     - DB_DUMP_BEGIN=2300 # Backup startet immer um 23 Uhr
  #     - DB_DUMP_TARGET=/db
  #     - DB_SERVER=bookstack-db
  #     - DB_USER=bookstack
  #     - DB_PASS= # Starkes Passwort von MYSQL_PASSWORD
  #   user: "0" # FÃ¼hrt Backup als root User durch - ggf. anpassen

  bookstack-app:
    image: solidnerd/bookstack
    container_name: bookstack-app
    restart: always
    volumes:
      - /var/docker/bookstack/app/uploads:/var/www/bookstack/public/uploads
      - /var/docker/bookstack/app/storage-uploads:/var/www/bookstack/public/storage
    environment:
      - DB_HOST=bookstack-db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD= # Hier das Passwort von MYSQL_PASSWORD aus dem Datenbankcontainer setzen
    labels:
      - "traefik.backend=bookstack"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:bookstack.example.com" # URL entsprechend anpassen!
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge