---
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout:1.15.39
    container_name: freescout-app
    restart: unless-stopped
    links:
      - freescout-db
    volumes:
      - /var/docker/freescout/data:/data
      - /var/docker/freescout/logs/:/www/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ZABBIX_HOSTNAME=freescout-app
      - DB_HOST=freescout-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - SITE_URL=https://${FREESCOUT_URL}
      - ADMIN_EMAIL=${ADMIN_NAME}
      - ADMIN_PASS=${ADMIN_PASSWORD}
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
      # - TIMEZONE=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout.entrypoints=websecure"
      - "traefik.http.routers.freescout.rule=Host(`${FREESCOUT_URL}`)"
      - "traefik.http.routers.freescout.tls=true"
      - "traefik.http.routers.freescout.tls.certresolver=default"
      - "traefik.http.routers.freescout.middlewares=secHeaders@file"
      - "traefik.http.services.freescout.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

  freescout-db:
    image: tiredofit/mariadb:10.7
    container_name: freescout-db
    restart: unless-stopped
    volumes:
      - /var/docker/freescout/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ROOT_PASS=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - ZABBIX_HOSTNAME=freescout-db

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
