---
version: "3"
services:
  calibre:
    image: linuxserver/calibre:5.43.0
    container_name: calibre
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/calibre/config:/config
    environment:
      - PUID=1000
      - PGID=1000

  calibre-web:
    image: linuxserver/calibre-web:2021.12.16
    container_name: calibre-web
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/calibre-web/config:/config
      - /var/docker/calibre/config/Calibre-Bibliothek:/books
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    depends_on:
      - calibre
    ports:
      - 8083:8083
