---
version: '3'

services:
  phpipam-db:
    image: mariadb:10.6
    container_name: phpipam-mysql
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/data/phpipam/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1  # Behebt die bekannten Startprobleme der Datenbank

  phpipam-phpipam:
    image: pierrecdn/phpipam:latest
    container_name: phpipam-phpipam
    restart: unless-stopped
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ENV_MYSQL_HOST=phpipam-db
    depends_on:
      - phpipam-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpipam.entrypoints=websecure"
      - "traefik.http.routers.phpipam.rule=Host(`${PHPIPAM_URL}`)"
      - "traefik.http.routers.phpipam.tls=true"
      - "traefik.http.routers.phpipam.tls.certresolver=default"
      - "traefik.http.routers.phpipam.middlewares=secHeaders@file"
      - "traefik.http.services.phpipam.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
