version: "3"
services:

  wikijs-db:
    image: postgres:11-alpine
    container_name: wikijs_db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/wikijs/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    logging:
      driver: "none"

  wikijs-app:
    image: requarks/wiki:2
    container_name: wikijs-app
    restart: unless-stopped
    depends_on:
      - wikijs-db
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs-db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=wiki
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.wikijs-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wikijs-http.entrypoints=web"
      - "traefik.http.routers.wikijs-http.rule=Host(`${WIKIJS-URL}`)"
      - "traefik.http.routers.wikijs-http.middlewares=wikijs-https@docker"
      - "traefik.http.routers.wikijs.entrypoints=web-secure"
      - "traefik.http.routers.wikijs.rule=Host(`${WIKIJS-URL}`)"
      - "traefik.http.routers.wikijs.tls=true"
      - "traefik.http.routers.wikijs.tls.certresolver=default"
      - "traefik.http.routers.wikijs.middlewares=secHeaders@file"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
