---
version: '3.3'

services:
  bookstack-db:
    image: mariadb:latest
    container_name: bookstack-db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/bookstack/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1

  bookstack-app:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/bookstack/app:/config
    links:
      - bookstack-db
    environment:
      - DB_HOST=bookstack-db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - APP_URL=https://${BOOKSTACK_URL}  # Zeile auskommentieren, wenn kein Traefik verwendet wird!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.rule=Host(`${BOOKSTACK_URL}`)"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=default"
      - "traefik.http.routers.bookstack.middlewares=secHeaders@file"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
