---
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.17.0
    container_name: uptime-kuma
    volumes:
      - /var/docker/uptime-kuma/config:/app/data
    ports:
      - 3001:3001