---
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    volumes:
       - /var/docker/bitwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bitwarden-https.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-http.rule=Host(`bitwarden.example.com`)" #Domain anpassen
      - "traefik.http.routers.bitwarden-http.middlewares=bitwarden-https@docker"
      - "traefik.http.routers.bitwarden.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.example.com`)" #Domain anpassen
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.tls.certresolver=default"
      - "traefik.http.routers.bitwarden.middlewares=secHeaders@file"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
