---
version: "3"
services:
  recipes-db:
    image: postgres:14-alpine
    container_name: recipes-db
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=${RECIPES_PSQL_PASSWORD}
      - POSTGRES_DB=recipes

  recipes-app:
    image: vabene1111/recipes
    container_name: recipes-app
    restart: unless-stopped
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - recipes-db
    environment:
      - SECRET_KEY=${RECIPES_SECRET}
      - POSTGRES_HOST=recipes-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=${RECIPES_PSQL_PASSWORD}
      - POSTGRES_DB=djangodb
      - ALLOWED_HOSTS=*
      - GUNICORN_MEDIA=0
      - DEBUG=0

  recipes-web:
    image: nginx:mainline-alpine
    container_name: recipes-web
    restart: unless-stopped
    depends_on:
      - recipes-app
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - ./staticfiles:/static
      - ./mediafiles:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.entrypoints=websecure"
      - "traefik.http.routers.recipes.rule=Host(`${RECIPES_URL}`)"
      - "traefik.http.routers.recipes.tls=true"
      - "traefik.http.routers.recipes.tls.certresolver=default"
      - "traefik.http.routers.recipes.middlewares=secHeaders@file"
      - "traefik.http.services.recipes.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
