---
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.9.1
    container_name: uptime-kuma
    volumes:
      - /var/docker/uptime-kuma/config:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.updatekuma.entrypoints=websecure"
      - "traefik.http.routers.updatekuma.rule=Host(`${UPTIMEKUMA_URL}`)"
      - "traefik.http.routers.updatekuma.tls=true"
      - "traefik.http.routers.updatekuma.tls.certresolver=default"
      - "traefik.http.routers.updatekuma.middlewares=secHeaders@file"
      - "traefik.http.services.updatekuma.loadbalancer.server.port=3001"
    networks:
      - traefik_proxy
      - uptime-kuma

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  uptime-kuma:
    driver: bridge
