---
version: "3"

services:
  freshrss-db:
    image: postgres:16
    container_name: fressrss-db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/freshrss/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=freshrss

  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    restart: unless-stopped
    depends_on:
      - freshrss-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/freshrss/data:/var/www/FreshRSS/data
      - /var/docker/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.rule=Host(`${FRESHRSS_URL}`)"  # Domain anpassen
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.routers.freshrss.tls.certresolver=default"
      - "traefik.http.routers.freshrss.middlewares=default@file"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
