---
version: "3"
services:
  calibre:
    image: linuxserver/calibre:6.9.0
    container_name: calibre
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/calibre/config:/config
    environment:
      - PUID=1000
      - PGID=1000

  calibre-web:
    image: linuxserver/calibre-web:2021.12.16
    container_name: calibre-web
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/calibre-web/config:/config
      - /var/docker/calibre/config/Calibre-Bibliothek:/books
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    depends_on:
      - calibre
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.rule=Host(`${CALIBRE_URL}`)"
      - "traefik.http.routers.calibre.tls=true"
      - "traefik.http.routers.calibre.tls.certresolver=default"
      - "traefik.http.routers.calibre.middlewares=secHeaders@file"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
